name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm ci
          npm run build

      - name: List directory
        run: ls -la

      - name: Zip Folder
        run: |
          zip -r ${{ github.event.repository.name }}.zip . -x ".git/*" ".github/*" "node_modules/*" ".gitignore" ".editorconfig" ".distignore" ".phpcs.xml" "composer.json" "composer.lock" "package.json" "package-lock.json"
          ls -la ${{ github.event.repository.name }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
